// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFundraising(arg1) {
  return window['go']['app']['App']['CreateFundraising'](arg1);
}

export function DeleteFundraising(arg1) {
  return window['go']['app']['App']['DeleteFundraising'](arg1);
}

export function GetFundraisingList() {
  return window['go']['app']['App']['GetFundraisingList']();
}

export function SyncFundraising(arg1, arg2) {
  return window['go']['app']['App']['SyncFundraising'](arg1, arg2);
}
