// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fundraising} from '../models';

export function CreateFundraising(arg1:fundraising.FundraisingURL):Promise<number>;

export function GetFundraisingList():Promise<Array<fundraising.FundraisingWithHistory>>;

export function SyncFundraising(arg1:number):Promise<void>;
